server:
  port: 8081
  servlet:
    context-path: /better-reads-app

spring:
  application:
    name: better-reads-application
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientID>
            client-secret: <clientSecret>
  data:
    cassandra:
      keyspace-name: <keyspace-name>
      username: <client-id>
      password: <secret>
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
    id: <datacenter-id>
    region: <region>
    keyspace: <keyspace-name>
    application-token: <token>

app:
  cover-image-base-url: https://covers.openlibrary.org/b/id/
  search-base-url: https://openlibrary.org/search.json
  # To enable logging for the request & response of any internal api call(s) to this application
  internal-logger-enable: false
  # WebClient configurations
  web-client:
    # Http request connection timeout: default is 10000 (in milliseconds)
    connection-timeout: 10000
    # Http response read timeout: default is 10000 (in milliseconds)
    read-timeout: 10000
    # MemoryBufferSize calculated as: 10 * 1024 * 1204 = 1048576 Byte = 10 MB, default is 256 KB & -1 is for unlimited
    max-memory-buffer-size: 10485760
    # To enable logging for the request & response of any external api call(s)
    logger-enable: false

# Define custom logging configurations in this logback.xml file as required
#logging:
#  config: /opt/akikr/config/better-reads-application/logback.xml
