spring:
  application:
    name: better-reads-application
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientID>
            client-secret: <clientSecret>

server:
  port: 8081
#  servlet:
#    context-path: /better-reads-app
